server:
  port: 8191

spring:
  cloud:
    config:
      server:
        git: 
          uri: https://github.com/sahanmaduka414/microservice-cloud-config
          search-paths:
          - 'service-config/*service'
          